name: liconv
channels:
  - pytorch
  - defaults
dependencies:
  - appdirs=1.4.4=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bottleneck=1.3.7=py38h9128911_0
  - brotli-python=1.0.9=py38hd77b12b_8
  - ca-certificates=2025.11.4=haa95532_0
  - certifi=2024.8.30=py38haa95532_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - colorama=0.4.6=py38haa95532_0
  - freetype=2.13.3=h0620614_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.7=py38haa95532_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - joblib=1.4.2=py38haa95532_0
  - jpeg=9f=ha349fce_0
  - lcms2=2.16=hb4a4139_0
  - lerc=3.0=hd77b12b_0
  - libdeflate=1.17=h2bbff1b_1
  - libffi=3.4.4=hd77b12b_1
  - libpng=1.6.50=h46444df_0
  - libtiff=4.5.1=hd77b12b_0
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.3.2=h3d04722_1
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - mkl=2023.1.0=h6b88ed4_46358
  - mkl-service=2.4.0=py38h2bbff1b_1
  - mkl_fft=1.3.8=py38h2bbff1b_0
  - mkl_random=1.2.4=py38h59b6b97_0
  - numexpr=2.8.4=py38h7b80656_1
  - numpy=1.24.3=py38h79a8e48_1
  - numpy-base=1.24.3=py38h8a87ada_1
  - openjpeg=2.5.2=hae555c5_0
  - openssl=3.0.18=h543e019_0
  - packaging=24.1=py38haa95532_0
  - pandas=1.4.4=py38hd77b12b_0
  - pillow=10.4.0=py38h827c3e9_0
  - pip=24.2=py38haa95532_0
  - platformdirs=3.10.0=py38haa95532_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pysocks=1.7.1=py38haa95532_0
  - python=3.8.20=h8205438_0
  - python-dateutil=2.9.0post0=py38haa95532_2
  - pytz=2024.1=py38haa95532_0
  - requests=2.32.3=py38haa95532_0
  - scikit-learn=1.3.0=py38h4ed8f06_1
  - scipy=1.10.1=py38hdcfc7df_1
  - setuptools=75.1.0=py38haa95532_0
  - six=1.16.0=pyhd3eb1b0_1
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2021.8.0=h59b6b97_0
  - threadpoolctl=3.5.0=py38h9909e9c_0
  - tqdm=4.66.5=py38h9909e9c_0
  - typing_extensions=4.11.0=py38haa95532_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.2.3=py38haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.44.0=py38haa95532_0
  - win_inet_pton=1.1.0=py38haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h56299aa_0
  - cpuonly=2.0=0
  - pytorch=1.10.1=py3.8_cpu_0
  - pytorch-mutex=1.0=cpu
  - torchvision=0.11.2=py38_cpu
  - pip:
    - brotli==1.0.9
    - torch==1.10.1

